### ISSUE TITLE
Fix comments

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-superhero-blog#41]
Current comment system is broken in many ways:
* Does not work
* Stores comments as content
* Inconsistent form
* Too many options (no real editor)

Actions:
- [x] Use "discussion" app from market as starting point for logic and handling
- [x] [Remove content type](https://github.com/enonic/app-superhero-blog/issues/59)
- [x] Setup storage of comments in separate repo (use best practice naming conventions)
- [x] [Better handling of logged in vs not (require login to comment?)](https://github.com/enonic/app-superhero-blog/issues/60)
- [x] [Update all listings ](https://github.com/enonic/app-superhero-blog/issues/61)
- [x] [Use superhero styling](https://github.com/enonic/app-superhero-blog/issues/62)
- [ ] Verify escaping in new code
- [ ] [Fix async display update after posting / editing a comment](https://github.com/enonic/app-superhero-blog/issues/63)
- [ ] [Comments always on](https://github.com/enonic/app-superhero-blog/issues/98)
- [ ] [Captcha](https://github.com/enonic/app-superhero-blog/issues/109)

**Comment by espen42** [comment]
Todo:

- [ ] adapt styling, 
- [ ] remove selectable styling in site.xml, 
- [ ] convert data, 
- [ ] remove old comments stuff
- [ ] is repo name best-practice now? `{app.name}.comments`

**Comment by espen42** [comment]
@sigdestad, jeg bruker repo-navnet `{app.name}.comments` til kommentarene nå, men et annet alternativ er jo å legge `.comments` til navnet til repoet som opprettes fra importen - altså `com.enonic.cms.sample-blog.comments` da. Noen mening om best practice på det (evt motsatt: endre det importerte reponavnet)?

**Comment by espen42** [comment]
@sigdestad Hva med markup-mulighetene som var i forrige kommentarsystem, vil vi beholde det? <b>, <a> osv...

**Comment by sigdestad** [comment]
La oss begynne uten, dvs alt escapes.

**Comment by espen42** [comment]
Høres bra ut
